# Useful numbers {.unnumbered}

## Units

1.  Radiometric units represent physical energy (e.g., radiance has units of watts $sr^{-1}~m^{-2}$)
2.  Colorimetric units adjust radiometric units for visual wavelength sensitivity (e.g. luminance has units of $\text{cd m}^{-2}$ scotopic units are proportional to rod absorptions; photopic luminance units are proportional to a weighted sum of the L and M cone absorptions
3.  Typical ambient luminance levels (in $\text{cd m}^{-2}$): starlight $10^{-3}$; moonlight $10^{-1}$; indoor lighting $10^{2}$; sunlight $10^{5}$; max intensity of common CRT monitors, $10^{2}$
4.  One Troland (Td) of retinal illumination is produced on the retina when the eye looks at a surface of 1 $\text{cd m}^{-2}$ through a pupil of area $1~mm^{2}$.
5.  Lens focal length: f (meters); lens power $=1/f$ (diopters)
6.  Conversion of linear units (X) to decibels: $Y=20~log~10(X)$; a change of 0.3 log10 units is a factor of 2, or 6 dB

## Image Formation

1.  The eyes are 6 cm apart and half-way down the head 
2.  Visual angle of the sun or moon $=0.5$ deg 
3.  At arm's length: thumbnail $=1.5$ deg; thumb joint $=2.0$ deg; fist $=8-10~deg$ 
4.  Monocular visual field measured from central fixation: 160 deg (w) x 175 deg (h) 
5.  Binocular visual field measured from central fixation: 200 deg (w) x 135 deg (h) 
6.  Region of binocular overlap: 120 deg (w) x 135 deg (h) 
7.  Range of pupil diameters: 2mm - 8mm. 
8.  Refractive indices: air 1.000; glass 1.520; water 1.333; cornea 1.376 
9.  Optical power (diopters): cornea, 43; lens, 20 (relaxed); whole eye, 60 
10. Change in power due to accommodation, 8 diopters 
11. Axial chromatic aberration over the visible spectrum: 2 diopters

## Retina

1.  Retinal size: $5~cm\times5$ cm; 0.4 mm thick
2.  One degree of visual angle $=0.3$ mm on the retina
3.  Number of cones in each retina: $5\times10^{6}$
4.  Number of rods in each retina: $10^{8}$
5.  Diameter of the fovea: 1.5 mm (5.2 deg); rod-free fovea: 0.5 mm (1.7 deg); foveola (rod-free, capillary-free fovea): 0.3 mm (1 deg); size of the optic nerve head: $1.5~\text{mm}\times2.1~mm$ (5 deg (w) x 7 deg (h)) location of the optic nerve head: 15 deg nasal
6.  Peak cone density: $1.6\times10^{5}~cones/\text{mm}^{2};$
7.  Foveal cone size: 1-4 $\mu \text{m}$ $(diameter)\times50-80~\mu \text{m}$ (length); extrafoveal cone size: 4-10 $\mu \text{m}$ (diameter) x 40 $\mu \text{m}$ (length)
8.  Size of rods near fovea: 1 $\mu \text{m}$ (diameter) x 60 $\mu \text{m}$ (length)
9.  S cone spacing (foveal): 10 arc min
10. L and M cone spacing (foveal): 0.5 arc min
11. Number of $(L+M)$ cones / Number of $S~cones=14$ (though the ratio may be higher in the foveola)
12. $1.5\times10^{6}$ optic nerve fibers/retina; ratio of receptors to ganglion cell in fovea 1:3; ratio of receptors to ganglion cells for whole retina, 125:1

## Cortex

1.  Area of entire cortex: $1.3\times10^{5}~\text{mm}^{2}$ 1.7 mm thick
2.  Total number of cortical neurons: $10^{10}$; density: $10^{5}$ neurons $/\text{mm}^{3}$
3.  Synapses: $5\times10^{8}$ synapses $/\text{mm}^{3}$ $4\times10^{3}$ synapses/neuron;
4.  Axons: 3 kilometers $/\text{mm}^{3}$
5.  Number of corpus callosum fibers: $5\times10^{8}$
6.  Number of macaque visual areas: 30
7.  Size of each area V1: 3cm by 8 cm
8.  Half of area V1 represents the central 10 deg (2% of the visual field)
9.  Width of a human ocular dominance column 0.5-1.0 mm; width of a macaque ocular dominance column 0.3 mm

## Sensitivity

1.  Minimum number of absorptions for: scotopic detection 1-5; detectable electrical excitation of a rod 1; photopic detection 10-15
2.  The number of photoisomerisations per rod (per sec?) required to saturate the retinal rod circuit: 1
3.  Following exposure to a sunny day, dark adaptation to a moonless night involves: 10 minutes (photopic); 40 minutes (scotopic); change in visual sensitivity 6 log10 units $\mu \text{m}$
4.  Highest detectable spatial frequency at high ambient light levels, 50-60 cpd; low ambient light levels, 20-30 cpd
5.  The contrast threshold (Delta $L/L)$ for a static edge at photopic luminances is 1%.
6.  Highest detectable temporal frequency: high ambient large field, 80 Hz; low ambient, large field 40 Hz.
7.  Typical localization threshold: 6 arc sec (0.5 $\mu \text{m}$ on the retina)
8.  Minimum temporal separation needed to discriminate two small, brief light pulses from a single equal-energy pulse: 15-20 ms
9.  Stereoscopic depth discrimination: step threshold, 3 arc sec; point threshold, 30 arc sec

## Color

1.  Visible spectrum: 370-730 nm
2.  Peak wavelength sensitivity: 507nm (scotopic) and 555 nm (photopic)
3.  Spectral equilibrium hues: 475 nm (blue), 500 nm (green), 575 nm (yellow), no spectral equilibrium red
4.  Number of basic English color names: 11
5.  Incidence of: anomalous trichromacy, $10^{-2}$ (male), $10^{-4}$ (female); protanopia and deuteranopia, $10^{-2}$ (male), $10^{-4}$ (female); tritanopia, $10^{-4}$; rod monochromacy, $10^{-4}$; cone monochromacy, $10^{-5}$
