## Retinal anatomy notes

Big picture about fovea and periphery.

Dave Brainard alerted me to recent Dacey reporting that the number of types of ganglion cell sin the primate fovea, and the connections of those cells, differs from the periphery.  This was presented in an ARVS paper fro

This is the classic two visual system idea.  The fovea is not the same as the periphery, only higher resolution.  It is fundamentally different and provides different signals to the cortex.

What would this mean for the cortical processing units?  Should we expect that they are different too?  If so, in what way?  Trevarthian?  Old two system ideas tied to midget/parasol.  But different.


### Connectomics Notes from Irene about the foveal anatomy

The goal of connectomics is to build complex networks of neurons in a defined region, such as the retina, including all of the synapses and sometimes gap junctions between every cell. Connectomics involves the development of large data models and 3D digital reconstructions of retinal neuron networks, called connectomes, in order to categorize and analyze the complete structural and functional wiring. Understanding the complete neuronal map is critical for understanding what happens to the retina and how this affects vision when some parts of the system fail, such as during retinal degeneration and other neural pathologies (Sigulinsky, Pfeiffer, and Jones 2024). Furthermore, the compact and highly ordered nature of the retina makes it an ideal model for simulating neural networks across the central nervous system.
	At its core, retinal connectomics investigates the connections between retinal neurons –photoreceptors, bipolar cells, amacrine cells, and ganglion cells– as well as between retinal neurons and support cells –vascular cells and glial cells. 

	Connectomics is a relatively new field because it is dependent on relatively recent technological advancements that allow high-resolution imaging of neurons in the retina. The increasingly comprehensive and detailed formation of these connectomes are largely driven by electron microscopy (EM) technologies (i.e. transmission electron microscopy (TEM) and serial block-face scanning electron microscopy (SBF-SEM)) as well as many new data interpretation tools (Sigulinsky, Pfeiffer, and Jones 2024; Marc et al 2013; Ware 1975). 3D reconstruction is achieved through taking microscale cross-sectional images, compiling them, and interpreting them. Before automation, this process was too tedious and labor intensive to realistically analyze and store such large data sets. Thus, advances in connectomics really started when EM methods became more automated and capable of high throughput (serial sectioning, mosaicking), and enabling large 3D volumes and when computational tools improved for aligning, stitching, registering, annotating, and rendering huge datasets.
In practice, no study has reconstructed a complete connectome of the entire retina. The comprehensive retinal connectomes have only started being published 15 years ago, and they often individually focus on a limited area or number of layers in the retina or one of the motifs and circuits underlying a particular function such as color, motion perception, or circadian rhythm entrainment. These circuits send images to the brain simultaneously, contributing to the retina’s ability for parallel processing, which is essential for our ability to process large volumes of visual information near instantaneously. 
The first retinal connectome (RC1) was created from TEM images of a rabbit’s inner plexiform layer and spanned the inner nuclear and ganglion cell layers at 2 nm resolution. To capture the 0.243 mm cylinder of retina, the project required 5 months of TEM beam time and 16.4 Tb of raw storage. It included over 300 bipolar cells (BCs), 300 Müller cells (MCs), 39 AII ACs, over 100 ACs, and 20 ganglion cells (GCs); every cell can be reconstructed (Marc et al 2013; Anderson et al 2011). 
Since then, several more retinal connectomes have been constructed attempting to target different model organisms, areas or layers of the retina, and functional circuits. 


Connectome RC1 slice 001. Composed of >1000 high-resolution TEM tiles, the slice is augmented with a transparency mapping simultaneously displaying GABA (red), glycine (green), glutamate (blue), and the logical AND of glutamine and taurine signals as a dark gold alpha channel. GABA+ (red) neurons are ACs, while glycine+ (green) neurons are either ACs or an ON cone BC subset. Glutamate+ (blue) neurons are largely BCs. Image width, 243 μm. From Anderson et al. (2011).

	Dennis Dacey’s work on retinal connectomics is concentrated on the circuits detecting, encoding, processing, and transmitting signals to the brain that are involved in color vision in macaque monkeys and humans. Our trichromatic color processing is divided into two major opponent pathways: the blue-yellow opponent pathway and the red-green opponent pathway. Dacey’s work in the 1990s establishes the blue-yellow pathway that begins with excitatory signals from short-wavelength cones (S-cones) and inhibitory signals from long and medium wavelength cones (L and M cones) that cascade through the small bistratified ganglion cell type (Dacey and Lee 1994, Dacey 1996). More recently, Dacey’s team has identified connections between blue cone bipolar cells (BB cells) and up to three different kinds of ganglion cells in the inner plexiform layer (IPL): the small bistratified ganglion cells previously associated with this pathway, large bistratified ganglion cells that also receive input from both ON and OFF midget bipolar cells, and ON-midget ganglion cells. It is generally understood that in non-human primates, midget bipolar cells exclusively synapse with midget ganglion cells, and are responsible for the red-green color opponent pathway as well as some achromatic spatial vision. Therefore, this connection in the circuitry in the IPL suggests that S cone signals must be summed with an L vs. M opponent signal and that the two color opponent pathways merge at the axon terminals of blue cone bipolar cells (Kim, Packer, and Dacey 2024). 


Identification of a large field bistratified ganglion cell type postsynaptic to S-ON bipolar (BB) cells. (A) A single BB cell (light blue) identified by its distinctive dendritic morphology and targeted connection with a sparsely distributed population of cone synaptic pedicles (violet; S cone 6) together with its axonal stratification deep in the IPL near the border with the GCL where it synapsed profusely with the small bistratified ganglion cell (SBGC, gold). This unique conjunction of morphological features established the identity of the three main cell types of the S-ON pathway: S cones, S-ON, or “blue-cone” bipolar (BB) cells, and small bistratified ganglion cells. To the right and overlapping this small bistratified cell is another bistratified ganglion cell (red) that received input from this BB cell; we identified this as a large bistratified cell based on its larger dendritic field and sparse input from 4 BB cells. From Kim, Packer, and Dacey (2024).	

Origin of parallel chromatic pathways from the S-ON bipolar (BB) cell synaptic output. (A) Reconstruction of the synaptic output of a single BB cell (ribbon synapse locations indicated by small balls within the axon terminal), exemplifies the main findings of this study. Most synapses are presynaptic to the small bistratified cell (gold balls; 69 synapses; 78.4% of total). A smaller number of synapses distribute to either the large bistratified ganglion cell (red balls; 12 synapses; 13.6% of total) or the inner-ON midget ganglion cell (green balls, 7 synapses; 8% of total). Note that not every BB cell contacted all three ganglion cell types (Table 1) and that the majority of inner-ON midget ganglion cells do not receive BB cell input, but when this synapse occurs it provides a significant fraction of the total input to a given midget ganglion cell (SI Appendix, Tables S2 and S7). (B–D) Hypothesized receptive field spatiochromatic 2D gaussian profiles for the two novel chromatic pathways, compared to that for the small bistratified cell. (B) Small bistratified cell shows S-ON vs. L+M-OFF cone opponency (Fig. 1B). (C) large bistratified ganglion cell, receptive field center will combine moderate S-ON input with L vs. M opponency derived from midget bipolar input. L vs. M opponency assumes surround cancellation of the weaker cone input to the receptive field surround (for details of mechanism see refs. 15 and 16). (D) ON-midget ganglion cell, S+L vs. M or S+M vs. L opponency, assumes a small S-ON input combined with L vs. M cone opponency (15). From Kim, Packer, and Dacey (2024).

	More recently, a branch of connectomics called pathoconnectomics, has risen to study retinal circuitry when it degrades or changes due to disease. Researchers at the Moran Eye Center at the University of Utah, the same group that developed the first retinal connectome (RC1), were also the first to develop a pathoconnectome for a rabbit with early-stage retinitis pigmentosa (RPC1). Pfeiffer et al (2020) was able to compare the connectomes between RC1 (non-affected rabbit control) and RPC1 (retinitis pigmentosa-affected rabbit) to find that rewiring of retinal networks happens before complete loss of photoreceptor input, retinal neurites synapse with expected and novel partners, and novel gap junctions are formed by rod bipolar cells early in retinal degeneration. Beyond studying neural degeneration in the eye, the retinal pathoconnectome can be used to understand general principles of neural degeneration in the other areas of the general central nervous system. 

	The field of connectomics faces several key challenges that slow its progress. Technological demands such as large volumes of data at high resolutions require a lot of time, energy, and space, think months to years of raw data collection and tens to hundreds of terabytes of storage. Classification of cells and synapse and gap junction annotation is also time-intensive and laborious. Automation tools have been developed to tackle this issue (i.e. Viking, Knossos, TrakEM2), but inaccuracies still arise, which means that researchers have to check the computer’s work. There are also interpretation limitations to extrapolating functional meaning or generalizability from connections within a neural network. 
	Despite these challenges, connectomics has revealed new knowledge about bipolar and amacrine cell connectivity, novel retinal cell types, neuroplasticity during retinal degeneration, and more. Importantly, retinal connectomics and the development of connectome-building tools serves as a model for studying neural circuitry throughout the brain and central nervous system, and can play a pivotal role in creating therapies for neural degenerative diseases such as retinitis pigmentosa, Parkinson’s, and Alzheimer's. 

References: 

Sigulinsky CL, Pfeiffer RL, Jones BW. Retinal Connectomics: A Review. Annu Rev Vis Sci. 2024 Sep;10(1):263-291. doi: 10.1146/annurev-vision-102122-110414. PMID: 39292552.
Marc RE, Jones BW, Watt CB, Anderson JR, Sigulinsky CL, Lauritzen S, Retinal connectomics: Towards complete, accurate networks, Progress in Retinal and Eye Research, Volume 37, 2013, Pages 141-162, ISSN 1350-9462, https://doi.org/10.1016/j.preteyeres.2013.08.002.
Sjöstrand FS. 1958.. Ultrastructure of retinal rod synapses of the guinea pig eye as revealed by three-dimensional reconstructions from serial sections. . J. Ultrastruct. Res. 2:(1):122–70. 
Ware RW. 1975.. Three-dimensional reconstruction from serial sections. . Int. Rev. Cytol. 40::325–440. 
Y.J. Kim,O. Packer, & D.M. Dacey,  A circuit motif for color in the human foveal retina, Proc. Natl. Acad. Sci. U.S.A. 121 (36) e2405138121, https://doi.org/10.1073/pnas.2405138121 (2024).
Dacey, D., Lee, B. The 'blue-on' opponent pathway in primate retina originates from a distinct bistratified ganglion cell type. Nature 367, 731–735 (1994). https://doi.org/10.1038/367731a0
Dacey, D.M. (1996). Circuitry for color coding in the primate retina. Proceedings of the National Academy of Sciences.93(2), 582-588. https://doi.org/10.1073/pnas.93.2.582
Anderson JR, Jones BW, Watt CB, Shaw MV, Yang JH, Demill D, Lauritzen JS, Lin Y, Rapp KD, Mastronarde D, Koshevoy P, Grimm B, Tasdizen T, Whitaker R, Marc RE. Exploring the retinal connectome. Mol Vis. 2011 Feb 3;17:355-79. PMID: 21311605; PMCID: PMC3036568.
Pfeiffer RL, Anderson JR, Dahal J, Garcia JC, Yang JH, Sigulinsky CL, Rapp K, Emrich DP, Watt CB, Johnstun HAB, Houser AR, Marc RE, Jones BW, A pathoconnectome of early neurodegeneration: Network changes in retinal degeneration, Experimental Eye Research, Volume 199, 2020, 108196, ISSN 0014-4835, https://doi.org/10.1016/j.exer.2020.108196.
Pfeiffer, R.L., Jones, B.W. (2023). Retinal Pathoconnectomics: A Window into Neurodegeneration. In: Ash, J.D., Pierce, E., Anderson, R.E., Bowes Rickman, C., Hollyfield, J.G., Grimm, C. (eds) Retinal Degenerative Diseases XIX. Advances in Experimental Medicine and Biology, vol 1415. Springer, Cham. https://doi.org/10.1007/978-3-031-27681-1_43

